---

- name: load variables based on distribution type
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yaml'
    - '{{ ansible_os_family }}.yaml'
  tags:
    - 'cifs_vars'

- name: install cifs and dependencies
  import_tasks: installation.yaml
  tags:
    - 'cifs_installation'

- name: push cifs config
  import_tasks: configuration.yaml
  tags:
    - 'cifs_configuration'
